# Car Config File from nav2_pkg
sick: 0
livox: 0
bpearl: 0
rp_lidar: 0
ld06: 1
ld19: 0
webcam: 0
intel: 0
oakd: 0
myoakd: 1
zed: 0
artemis: 0
ublox: 0
vesc_with_odom: 0
vesc_without_odom: 1
adafruit: 0
adafruit_servo: 0
adafruit_continuous_servo: 0
esp32: 0
stm32: 0
bldc_sensor: 0
bldc_no_sensor: 0
